[package]
name = "deltavfs-hook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4"
anyhow = "1.0"
iced-x86 = "1.15.0"

[dependencies.windows]
version = "0.30.0"
features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_Console"
]
